

const config = {

  project_uuid: '19b1c1bd-792c-4fae-95df-528206c8b6ab',
  flHost: process.env.NODE_ENV === 'production' ? 'https://flatlogic.com/projects' : 'http://localhost:3000/projects',

    gitea_domain: process.env.GITEA_DOMAIN || 'gitea.flatlogic.app',
    gitea_username: process.env.GITEA_USERNAME || 'admin',
    gitea_api_token: process.env.GITEA_API_TOKEN || null,
    github_repo_url: process.env.GITHUB_REPO_URL || null,
    github_token: process.env.GITHUB_TOKEN || null,

    eventTypes: {
        COMMIT: 'PROJECT_DEV_COMMIT',
        COMMIT_STARTED: 'COMMIT_STARTED',
        COMMIT_FAILED: 'COMMIT_FAILED',
        COMMIT_COMPLETED: 'COMMIT_COMPLETED',
        REPO_INIT_COMPLETED: 'REPO_INIT_COMPLETED',
        REPO_INIT_STARTED: 'REPO_INIT_STARTED',
        REPO_INIT_FAILED: 'REPO_INIT_FAILED',
        REMOTE_REPO_CREATION_STARTED: 'REMOTE_REPO_CREATION_STARTED',
        REMOTE_REPO_CREATION_COMPLETED: 'REMOTE_REPO_CREATION_COMPLETED',
        REMOTE_REPO_CREATION_FAILED: 'REMOTE_REPO_CREATION_FAILED',
        FETCH_RESET_STARTED: 'FETCH_RESET_STARTED',
        FETCH_RESET_COMPLETED: 'FETCH_RESET_COMPLETED',
        RESET_TO_BRANCH_COMPLETED: 'RESET_TO_BRANCH_COMPLETED',
        RESET_TO_BRANCH_FAILED: 'RESET_TO_BRANCH_FAILED',
        VALIDATION_ERROR: 'VALIDATION_ERROR',
        DEPLOYMENT: 'DEPLOYMENT_STATUS',
        BUILD_ERROR: 'BUILD_ERROR',
        RUNTIME_ERROR: 'RUNTIME_ERROR',
        USER_ACTION: 'USER_ACTION',
        READ_PROJECT_TREE_STARTED: 'READ_PROJECT_TREE_STARTED',
        READ_PROJECT_TREE_COMPLETED: 'READ_PROJECT_TREE_COMPLETED',
        READ_PROJECT_TREE_FAILED: 'READ_PROJECT_TREE_FAILED',
        FILE_VALIDATION_STARTED: 'FILE_VALIDATION_STARTED',
        FILE_VALIDATION_COMPLETED: 'FILE_VALIDATION_COMPLETED',
    }
};

module.exports = config;
